const steps = [
  {
    number: '01',
    title: 'Describe Your Architecture',
    description:
      'Type or speak what you need: "A highly available EKS cluster with a managed node group, RDS Postgres with read replicas, and CloudFront CDN." CloudeArc understands context, scale, and best practices.',
    color: 'from-cyan-400 to-cyan-600',
  },
  {
    number: '02',
    title: 'AI Generates & Validates',
    description:
      'Our fine-tuned models produce complete IaC templates with modules, variables, and outputs. The policy engine simultaneously runs 200+ compliance checks and flags anything risky.',
    color: 'from-emerald-400 to-emerald-600',
  },
  {
    number: '03',
    title: 'Review, Tweak, Deploy',
    description:
      'Inspect the interactive diagram, adjust parameters via the visual editor, and open a PR directly into your repo. Your CI/CD pipeline takes it from there — fully automated.',
    color: 'from-teal-400 to-teal-600',
  },
];

function HowItWorks() {
  return (
    <section id="how-it-works" className="py-24 px-4 bg-white/[0.02]">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <p className="text-sm font-semibold text-emerald-400 uppercase tracking-widest mb-4">
            How It Works
          </p>
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold font-['Syne'] tracking-tight">
            From idea to infrastructure{' '}
            <span className="gradient-text">in 3 steps</span>
          </h2>
        </div>

        {/* Steps */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 relative">
          {/* Connecting Line (Desktop) */}
          <div className="hidden lg:block absolute top-16 left-[calc(16.67%+2rem)] right-[calc(16.67%+2rem)] h-px bg-gradient-to-r from-cyan-500/50 via-emerald-500/50 to-teal-500/50" />

          {steps.map((step, i) => (
            <div key={i} className="relative text-center">
              {/* Step Number Circle */}
              <div
                className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${step.color} flex items-center justify-center text-2xl font-bold font-['Syne'] mx-auto mb-6 shadow-lg relative z-10`}
              >
                {step.number}
              </div>

              <h3 className="text-xl font-semibold mb-3">{step.title}</h3>
              <p className="text-gray-400 leading-relaxed max-w-sm mx-auto">{step.description}</p>
            </div>
          ))}
        </div>

        {/* Code Preview Window */}
        <div className="mt-16 glass-card overflow-hidden max-w-3xl mx-auto">
          {/* Window Bar */}
          <div className="flex items-center gap-2 px-4 py-3 border-b border-white/10 bg-white/[0.03]">
            <div className="w-3 h-3 rounded-full bg-red-500/80" />
            <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
            <div className="w-3 h-3 rounded-full bg-green-500/80" />
            <span className="ml-3 text-xs text-gray-500 font-mono">main.tf — generated by CloudeArc</span>
          </div>
          {/* Code Content */}
          <div className="p-6 font-mono text-sm leading-relaxed overflow-x-auto">
            <pre className="text-gray-300">
              <code>{`<span class="text-gray-500"># Auto-generated by CloudeArc — Production Grade</span>
<span class="text-purple-400">module</span> <span class="text-cyan-400">"eks_cluster"</span> {
  <span class="text-gray-500">source</span>  = <span class="text-emerald-400">"terraform-aws-modules/eks/aws"</span>
  <span class="text-gray-500">version</span> = <span class="text-emerald-400">"~> 19.0"</span>

  <span class="text-gray-500">cluster_name</span>    = <span class="text-emerald-400">"prod-us-east-1"</span>
  <span class="text-gray-500">cluster_version</span> = <span class="text-emerald-400">"1.28"</span>

  <span class="text-gray-500">vpc_id</span>     = <span class="text-purple-400">module</span>.<span class="text-cyan-400">vpc</span>.<span class="text-amber-400">vpc_id</span>
  <span class="text-gray-500">subnet_ids</span> = <span class="text-purple-400">module</span>.<span class="text-cyan-400">vpc</span>.<span class="text-amber-400">private_subnets</span>

  <span class="text-gray-500">managed_node_groups</span> = {
    <span class="text-cyan-400">general</span> = {
      <span class="text-gray-500">instance_types</span> = [<span class="text-emerald-400">"t3.large"</span>]
      <span class="text-gray-500">min_size</span>       = <span class="text-amber-400">3</span>
      <span class="text-gray-500">max_size</span>       = <span class="text-amber-400">12</span>
      <span class="text-gray-500">desired_size</span>   = <span class="text-amber-400">3</span>
    }
  }

  <span class="text-gray-500">enable_irsa</span>              = <span class="text-purple-400">true</span>
  <span class="text-gray-500">cluster_endpoint_public_access</span> = <span class="text-purple-400">false</span>
}`}</code>
            </pre>
          </div>
        </div>
      </div>
    </section>
  );
}

export default HowItWorks;
